name: Testing Backend CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to avoid shallow clone issues

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11  # Update to Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Ensure pip is up-to-date
        pip install .  # Install project dependencies
        pip install coverage
    
    - name: Run tests
      run: |
        python -m coverage run -m unittest discover code

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
